{
  parserClass="dev.verloren.midnight.parser.CompactParser"
  psiPackage="dev.verloren.midnight.psi"
  psiImplPackage="dev.verloren.midnight.psi.impl"

  psiClassPrefix="Compact"
  psiImplClassSuffix="Impl"

  elementTypeHolderClass="dev.verloren.midnight.psi.CompactTypes"
  elementTypeClass="com.intellij.psi.tree.IElementType"
  tokenTypeClass="dev.verloren.midnight.lexer.CompactTokenType"

  parserUtilClass="dev.verloren.midnight.parser.CompactParserUtil"

  tokens = [
    PRAGMA           = "pragma"
    IMPORT           = "import"
    EXPORT           = "export"
    FROM             = "from"
    MODULE           = "module"
    PREFIX           = "prefix"
    ASSERT           = "assert"
    AS               = "as"
    CIRCUIT          = "circuit"
    CONST            = "const"
    CONSTRUCTOR      = "constructor"
    CONTRACT         = "contract"
    DEFAULT          = "default"
    DISCLOSE         = "disclose"
    ELSE             = "else"
    ENUM             = "enum"
    EXTERNAL         = "external"
    FOLD             = "fold"
    FOR              = "for"
    IF               = "if"
    IMPLEMENTS       = "implements"
    INCLUDE          = "include"
    LEDGER           = "ledger"
    MAP              = "map"
    NEW              = "new"
    OF               = "of"
    PAD              = "pad"
    PURE             = "pure"
    RETURN           = "return"
    SEALED           = "sealed"
    SLICE            = "slice"
    STRUCT           = "struct"
    TYPE             = "type"
    WITNESS          = "witness"
    EMIT             = "emit"
    TRUE             = "true"
    FALSE            = "false"
    ASSIGN           = "="
    PLUS_ASSIGN      = "+="
    MINUS_ASSIGN     = "-="
    PLUS             = "+"
    MINUS            = "-"
    STAR             = "*"
    EQEQ             = "=="
    NOTEQ            = "!="
    LT               = "<"
    LTE              = "<="
    GT               = ">"
    GTE              = ">="
    ARROW            = "=>"
    NOT              = "!"
    ANDAND           = "&&"
    OROR             = "||"
    RANGE            = ".."
    DOT              = "."
    SPREAD           = "..."
    QUESTION         = "?"
    COLON            = ":"
    LPAREN           = "("
    RPAREN           = ")"
    LBRACE           = "{"
    RBRACE           = "}"
    LBRACKET         = "["
    RBRACKET         = "]"
    COMMA            = ","
    SEMICOLON        = ";"
    HASH             = "#"
    AWAIT          = "await"
    BREAK          = "break"
    CASE           = "case"
    CATCH          = "catch"
    CLASS          = "class"
    CONTINUE       = "continue"
    DEBUGGER       = "debugger"
    DELETE         = "delete"
    DO             = "do"
    EXTENDS        = "extends"
    FINALLY        = "finally"
    FUNCTION       = "function"
    INTERFACE      = "interface"
    LET            = "let"
    NULL           = "null"
    PACKAGE        = "package"
    PRIVATE        = "private"
    PROTECTED      = "protected"
    PUBLIC         = "public"
    STATIC         = "static"
    SUPER          = "super"
    SWITCH         = "switch"
    THIS           = "this"
    THROW          = "throw"
    TRY            = "try"
    TYPEOF         = "typeof"
    VAR            = "var"
    VOID           = "void"
    WHILE          = "while"
    WITH           = "with"
    YIELD          = "yield"
    ARGUMENT       = "argument"
    EVAL           = "eval"
    EVENT          = "event"
    IN             = "in"
    INSTANCEOF     = "instanceof"
    IDENTIFIER
  ]
}
root ::= program

program ::= program_element* <<eof>>

program_element ::=
pragma_form


pragma_form ::= PRAGMA pragma_identifier version_expr SEMICOLON {pin=1}

private pragma_identifier ::= <<pragmaIdentifier>>

private version_expr ::= version_expr0 (OROR version_expr0)*

// Translated from: (Version-expression0 (version-expr0) ...)
private version_expr0 ::= version_term (ANDAND version_term)*

// Translated from: (Version-Term (version-term) ...)
version_term ::= version_atom                        // version-term-atom
               | NOT     version_atom                // version-term-not  (#\!)
               | LT      version_atom                // version-term-lt   (#\<)
               | LTE     version_atom                // version-term-le   ("<=")
               | GTE     version_atom                // version-term-ge   (">=")
               | GT      version_atom                // version-term-gt   (#\>)
               | LPAREN  version_expr  RPAREN        // version-term-parens

version_atom ::= VERSION_LITERAL
               | nat_literal

private nat_literal ::= DECIMAL_LITERAL | HEX_LITERAL | BINARY_LITERAL | OCTAL_LITERAL


