package dev.verloren.midnight.lexer

import com.intellij.psi.TokenType
import com.intellij.psi.tree.IElementType
import dev.verloren.midnight.psi.CompactTypes

/**
 * Thin alias wrapper over the generated [CompactTypes] constants.
 *
 * [CompactTypes] (generated by Grammar-Kit from `Compact.bnf`) is the single
 * source of truth for every `IElementType` referenced by the grammar: it is
 * what the generated parser/PSI code checks against by object identity, and
 * `Compact.flex` returns those exact instances. This object exists purely so
 * existing call sites (syntax highlighter, brace matcher, etc.) can keep
 * referring to `CompactTokenTypes.X` without having to import `CompactTypes`
 * everywhere - it must never construct its own `IElementType` for any token
 * that also appears in the grammar.
 *
 * The only genuine exceptions are tokens that are never referenced by any
 * BNF rule (and therefore have no generated counterpart in [CompactTypes]):
 * whitespace, comments, and the various "unknown input" tokens, plus the two
 * framework-level types [TokenType.WHITE_SPACE] / [TokenType.BAD_CHARACTER].
 */
object CompactTokenTypes {

    // =========================================================
    // Keywords
    // =========================================================

    @JvmField
    val EXPORT: IElementType? = CompactTypes.EXPORT

    @JvmField
    val FROM: IElementType? = CompactTypes.FROM

    @JvmField
    val IMPORT: IElementType? = CompactTypes.IMPORT

    @JvmField
    val MODULE: IElementType? = CompactTypes.MODULE

    @JvmField
    val PREFIX: IElementType? = CompactTypes.PREFIX

    @JvmField
    val ASSERT: IElementType? = CompactTypes.ASSERT

    @JvmField
    val AS: IElementType? = CompactTypes.AS

    @JvmField
    val CIRCUIT: IElementType? = CompactTypes.CIRCUIT

    @JvmField
    val CONST: IElementType? = CompactTypes.CONST

    @JvmField
    val CONSTRUCTOR: IElementType? = CompactTypes.CONSTRUCTOR

    @JvmField
    val CONTRACT: IElementType? = CompactTypes.CONTRACT

    @JvmField
    val DEFAULT: IElementType? = CompactTypes.DEFAULT

    @JvmField
    val DISCLOSE: IElementType? = CompactTypes.DISCLOSE

    @JvmField
    val ELSE: IElementType? = CompactTypes.ELSE

    @JvmField
    val ENUM: IElementType? = CompactTypes.ENUM

    @JvmField
    val FOLD: IElementType? = CompactTypes.FOLD

    @JvmField
    val FOR: IElementType? = CompactTypes.FOR

    @JvmField
    val IF: IElementType? = CompactTypes.IF

    @JvmField
    val INCLUDE: IElementType? = CompactTypes.INCLUDE

    @JvmField
    val LEDGER: IElementType? = CompactTypes.LEDGER

    @JvmField
    val MAP: IElementType? = CompactTypes.MAP

    @JvmField
    val NEW: IElementType? = CompactTypes.NEW

    @JvmField
    val OF: IElementType? = CompactTypes.OF

    @JvmField
    val PAD: IElementType? = CompactTypes.PAD

    @JvmField
    val PRAGMA: IElementType? = CompactTypes.PRAGMA

    @JvmField
    val PURE: IElementType? = CompactTypes.PURE

    @JvmField
    val RETURN: IElementType? = CompactTypes.RETURN

    @JvmField
    val SEALED: IElementType? = CompactTypes.SEALED

    @JvmField
    val SLICE: IElementType? = CompactTypes.SLICE

    @JvmField
    val STRUCT: IElementType? = CompactTypes.STRUCT

    @JvmField
    val TYPE: IElementType? = CompactTypes.TYPE

    @JvmField
    val WITNESS: IElementType? = CompactTypes.WITNESS

    @JvmField
    val EMIT: IElementType? = CompactTypes.EMIT

    // =========================================================
    // Built-in Types
    // =========================================================

    @JvmField
    val BOOLEAN_TYPE: IElementType? = CompactTypes.BOOLEAN_TYPE

    @JvmField
    val BYTES_TYPE: IElementType? = CompactTypes.BYTES_TYPE

    @JvmField
    val FIELD_TYPE: IElementType? = CompactTypes.FIELD_TYPE

    @JvmField
    val OPAQUE_TYPE: IElementType? = CompactTypes.OPAQUE_TYPE

    @JvmField
    val UINT_TYPE: IElementType? = CompactTypes.UINT_TYPE

    @JvmField
    val VECTOR_TYPE: IElementType? = CompactTypes.VECTOR_TYPE

    @JvmField
    val JUBJUB_SCALAR_TYPE: IElementType? = CompactTypes.JUBJUB_SCALAR_TYPE

    @JvmField
    val SECP256K1_BASE_TYPE: IElementType? = CompactTypes.SECP256K1_BASE_TYPE

    @JvmField
    val SECP256K1_SCALAR_TYPE: IElementType? = CompactTypes.SECP256K1_SCALAR_TYPE

    // =========================================================
    // Literals
    // =========================================================

    @JvmField
    val TRUE: IElementType? = CompactTypes.TRUE

    @JvmField
    val FALSE: IElementType? = CompactTypes.FALSE

    @JvmField
    val VERSION_LITERAL: IElementType? = CompactTypes.VERSION_LITERAL

    @JvmField
    val DECIMAL_LITERAL: IElementType? = CompactTypes.DECIMAL_LITERAL

    @JvmField
    val BINARY_LITERAL: IElementType? = CompactTypes.BINARY_LITERAL

    @JvmField
    val OCTAL_LITERAL: IElementType? = CompactTypes.OCTAL_LITERAL

    @JvmField
    val HEX_LITERAL: IElementType? = CompactTypes.HEX_LITERAL


    @JvmField
    val STRING_LITERAL: IElementType? = CompactTypes.STRING_LITERAL

    @JvmField
    val IDENTIFIER: IElementType? = CompactTypes.IDENTIFIER

    // =========================================================
    // Operators
    // =========================================================

    @JvmField
    val ASSIGN: IElementType? = CompactTypes.ASSIGN

    @JvmField
    val PLUS_ASSIGN: IElementType? = CompactTypes.PLUS_ASSIGN

    @JvmField
    val MINUS_ASSIGN: IElementType? = CompactTypes.MINUS_ASSIGN

    @JvmField
    val PLUS: IElementType? = CompactTypes.PLUS

    @JvmField
    val MINUS: IElementType? = CompactTypes.MINUS

    @JvmField
    val STAR: IElementType? = CompactTypes.STAR

    // Any BNF rule does not reference SLASH and PERCENT, so Grammar-Kit
    // never generates a corresponding constant in CompactTypes - these two
    // remain the lexer's own instances.
    @JvmField
    val SLASH: IElementType = CompactTokenType("SLASH")

    @JvmField
    val PERCENT: IElementType = CompactTokenType("PERCENT")

    @JvmField
    val EQEQ: IElementType? = CompactTypes.EQEQ

    @JvmField
    val NEQ: IElementType? = CompactTypes.NOTEQ

    @JvmField
    val LT: IElementType? = CompactTypes.LT

    @JvmField
    val LTE: IElementType? = CompactTypes.LTE

    @JvmField
    val GT: IElementType? = CompactTypes.GT

    @JvmField
    val GTE: IElementType? = CompactTypes.GTE

    @JvmField
    val ARROW: IElementType? = CompactTypes.ARROW

    @JvmField
    val NOT: IElementType? = CompactTypes.NOT

    @JvmField
    val ANDAND: IElementType? = CompactTypes.ANDAND

    @JvmField
    val OROR: IElementType? = CompactTypes.OROR

    @JvmField
    val RANGE: IElementType? = CompactTypes.RANGE

    @JvmField
    val DOT: IElementType? = CompactTypes.DOT

    @JvmField
    val SPREAD: IElementType? = CompactTypes.SPREAD

//    @JvmField
//    val QUESTION = CompactTypes.QUESTION
//
//    @JvmField
//    val COLON = CompactTypes.COLON

    // =========================================================
    // Delimiters
    // =========================================================

    @JvmField
    val LPAREN: IElementType? = CompactTypes.LPAREN

    @JvmField
    val RPAREN: IElementType? = CompactTypes.RPAREN

    @JvmField
    val LBRACE: IElementType? = CompactTypes.LBRACE

    @JvmField
    val RBRACE: IElementType? = CompactTypes.RBRACE

    @JvmField
    val LBRACKET: IElementType? = CompactTypes.LBRACKET

    @JvmField
    val RBRACKET: IElementType? = CompactTypes.RBRACKET

    @JvmField
    val COMMA: IElementType? = CompactTypes.COMMA

    @JvmField
    val SEMICOLON: IElementType? = CompactTypes.SEMICOLON

//    @JvmField
//    val HASH = CompactTypes.HASH

    // =========================================================
    // Comments
    // =========================================================
    // Not referenced by any BNF rule - genuinely lexer-only tokens.

    @JvmField
    val LINE_COMMENT: IElementType = CompactTokenType("LINE_COMMENT")

    @JvmField
    val BLOCK_COMMENT: IElementType = CompactTokenType("BLOCK_COMMENT")

    // =========================================================
    // Whitespace & Special
    // =========================================================

    @JvmField
    val WHITE_SPACE: IElementType = TokenType.WHITE_SPACE

    @JvmField
    val BAD_CHARACTER: IElementType = TokenType.BAD_CHARACTER

    @JvmField
    val UNTERMINATED_STRING: IElementType = CompactTokenType("UNTERMINATED_STRING")

    @JvmField
    val UNTERMINATED_BLOCK_COMMENT: IElementType =
        CompactTokenType("UNTERMINATED_BLOCK_COMMENT")
}
